### ISSUE TITLE
openmpi: Permission Denied Error

### ISSUE THREAD

**Issue by smasoka** [SouthAfricaDigitalScience/OpenMPI-deploy#3]
Do you have an Idea of the error below?

/tmp/hudson3656222363984324720.sh: line 5: ./build.sh: Permission denied
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...
[BFA] Found failure cause(s):
[BFA] permissions from category permissions,
[BFA] Done. 0s
Finished: FAILURE

**Comment by brucellino** [comment]
Hey @smasoka for future reference, also please refer to the build number.

**Comment by brucellino** [comment]
This was due to build.sh not being chmod u+x. Seems this has been fixed though.
