### ISSUE TITLE
openmpi: Compiler tag

### ISSUE THREAD

**Issue by brucellino** [SouthAfricaDigitalScience/OpenMPI-deploy#4]
the check-build script does not create a modulefile specific to the compiler and version of mpi used. There is a different module for each version, but there should _also_ be a different version for the compilers used. 

E.g.
- openmpi/1.8.8-gcc-4.8.4
- openmpi/1.8.8-gcc-5.2.2

OR 
- openmpi-gcc5/1.8.8
- openmpi-gcc4/1.8.8

etc.

**Comment by smasoka** [comment]
I've edited, for each build, 
- openmpi/1.8.8-gcc-4.9.2
- openmpi/1.8.8-gcc-5.2.0
  modulefiles will be created and tested.

**Comment by brucellino** [comment]
fixed in build 14
