### ISSUE TITLE
Openmpi: not compiling with all GCC versions

### ISSUE THREAD

**Issue by smasoka** [SouthAfricaDigitalScience/OpenMPI-deploy#7]
```
Currently Loaded Modulefiles:
  1) ci              3) mpfr/3.1.2      5) gcc/4.8.4       7) torque/2.5.13
  2) gmp/5.1.3       4) mpc/1.0.1       6) gcc/4.9.2
REPO_DIR is 
/repo/generic/sl6/x86_64/openmpi/1.8.8
SRC_DIR is 
/repo/src/openmpi/1.8.8
WORKSPACE is 
/var/lib/jenkins/workspace/OpenMPI/ARCH/x86_64/GCC_VERSION/4.8.4/OS/sl6/SITE/generic/VERSION/1.8.8
SOFT_DIR is
/apprepo/generic/sl6/x86_64/openmpi/1.8.8
continuing from previous builds, using source at  /repo/src/openmpi/1.8.8/openmpi-1.8.8.tar.gz
GCC Version being used
/apprepo/generic/sl6/x86_64/gcc/4.9.2/bin/gfortran
/apprepo/generic/sl6/x86_64/gcc/4.9.2/bin/gcc
/apprepo/generic/sl6/x86_64/gcc/4.9.2/bin/g++
Configuring the build
```

This is our problem. After compiling with gcc-4.9.2, even when we load up gcc-4.8.4, 
4.9 is still the default. So we have to unload the current gcc version for the next build, just after  `make install` on build.sh

**Comment by smasoka** [comment]
Added 
`module unload gcc/$GCC_VERSION`
at the end on `build.sh` to unload the current gcc compiler to make way for the next one. 
Hope it works.

**Comment by smasoka** [comment]
```
GCC Version being used
/apprepo/generic/sl6/x86_64/gcc/4.9.2/bin/gfortran
/apprepo/generic/sl6/x86_64/gcc/4.9.2/bin/gcc
/apprepo/generic/sl6/x86_64/gcc/4.9.2/bin/g++
```

and 

```
Currently Loaded Modulefiles:
  1) ci              3) mpfr/3.1.2      5) gcc/4.8.4       7) torque/2.5.13
  2) gmp/5.1.3       4) mpc/1.0.1       6) gcc/4.9.2
```

Im not sure if the `module unload gcc/$GCC_VERSION` is not working or what, but gcc/4.9.2 is not unloaded at the end of make. 
So I'm trying compiling just for 4.8.4 to see whats happening.

**Comment by smasoka** [comment]
Okay so I had to change the order of loading modules
`toruqe/2.5.13` loads `gcc/4.9.2`, so if I want a different gcc I have to load it last. 

```
module load torque/2.5.13
module load gcc/$GCC_VERSION
```

this should work.

**Comment by brucellino** [comment]
you need to have the torque module load the GCC that it was actually built with. So, if torque was built with 4.9.2, it should that. This will then propagate to OpenMPI

**Comment by kennedydane** [comment]
Okay -- is there a good reason you need the same version of OpenMPI built with different versions of gcc? I remember Andy talking to the openmpi guys and they seemed to think that was a non issue -- even saying that you can swap between an icc compiled and a gcc compiled version...

**Comment by smasoka** [comment]
so it GCC 4.9.2 and 5.2.0

**Comment by brucellino** [comment]
> is there a good reason you need the same version of OpenMPI built with different versions of gcc?

We don't _need_ it, but if we used OpenMPI built with one version of GCC, and then we try to `mpicc`or `mpirun` another app with that using a _different_ GCC, I don't think that'll work.

**Comment by smasoka** [comment]
So building openmpi with the gcc versions used for building torque worked. 
Closing this issue.
